NSFL/NSFL/Models/Player/PlayerModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSFL.Models.Player
{
    public class Player
    {
        public string PlayerSeasonDrafted { get; set; }

        public string PlayerFirstName { get; set; }

        public string PlayerLastName { get; set; }

        public int PlayerTPE { get; set; }

        public string PlayerPosition { get; set; }

        public string PlayerProfileURL { get; set; }
    }

    public class PlayerFileLine
    {
        public PlayerFileLine()
        { }

        public PlayerFileLine(string playerLine)
        {
            PlayerLine = playerLine;
        }

        public string PlayerLine { get; set; }
    }
}

NSFL/NSFL/Models/Player/PlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NSFL.Models.Player
{
    public class PlayerViewModel
    {
        [DisplayName("Team")]
        public string TeamName { get; set; }

        [DisplayName("Drafted")]
        public string PlayerSeasonDrafted { get; set; }

        [DisplayName("First name")]
        public string PlayerFirstName { get; set; }

        [DisplayName("Last name")]
        public string PlayerLastName { get; set; }

        [DisplayName("TPE")]
        public int PlayerTPE { get; set; }

        [MaxLength(2)]
        [DisplayName("Position")]
        public string PlayerPosition { get; set; }

        [DisplayName("Name")]
        public string PlayerFullName
        {
            get
            {
                return string.Format("{0} {1}", PlayerFirstName, PlayerLastName);
            }
        }

        public string PlayerProfileURL { get; set; }
    }
}

NSFL/NSFL/Models/Stats/StatsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSFL.Models.Stats
{
    public class TeamTPEViewModel
    {
        public List<Team.TeamViewModel> Teams { get; set; }

        public List<Player.PlayerViewModel> AllPlayers { get; set; }
    }
}

NSFL/NSFL/Models/Team/TeamViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NSFL.Models.Team
{
    public class TeamViewModel
    {
        [MaxLength(50)]
        [DisplayName("Team name")]
        public string TeamName { get; set; }

        [DisplayName("Team TPE")]
        public int TeamTPE { get; set; }

        [DisplayName("Players")]
        public List<Player.PlayerViewModel> Players { get; set; }
    }
}

NSFL/NSFL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSFL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NSFL/NSFL/Controllers/StatsController.cs
using NSFL.Helpers;
using NSFL.Models.Player;
using NSFL.Models.Stats;
using NSFL.Models.Team;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSFL.Controllers
{
    public class StatsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TeamTPE()
        {
            var viewModel = new TeamTPEViewModel();
            viewModel.Teams = new List<TeamViewModel>();
            viewModel.AllPlayers = new List<PlayerViewModel>();

            var playerFiles = TeamHelper.GetTeamPlayerFiles();
            foreach (var file in playerFiles)
            {
                if (System.IO.File.Exists(System.Web.HttpContext.Current.Server.MapPath(file.Value)))
                {
                    var team = new TeamViewModel();
                    team.TeamName = file.Key;
                    team.Players = new List<PlayerViewModel>();

                    var lines = System.IO.File.ReadAllLines(System.Web.HttpContext.Current.Server.MapPath(file.Value));
                    foreach (var line in lines)
                    {
                        var playerFileLine = new PlayerFileLine(line);

                        var playerData = PlayerHelper.GetPlayerFromPlayerLine(playerFileLine);
                        if (string.IsNullOrEmpty(playerData.PlayerFirstName))
                        {
                            continue;
                        }

                        var player = new PlayerViewModel();
                        player.PlayerFirstName = playerData.PlayerFirstName;
                        player.PlayerLastName = playerData.PlayerLastName;
                        player.PlayerPosition = playerData.PlayerPosition;
                        player.PlayerSeasonDrafted = playerData.PlayerSeasonDrafted;
                        player.PlayerTPE = playerData.PlayerTPE;
                        player.TeamName = team.TeamName;
                        player.PlayerProfileURL = playerData.PlayerProfileURL;

                        team.Players.Add(player);
                        viewModel.AllPlayers.Add(player);
                    }

                    var teamTPE = 0;

                    // TODO: convert this to read from the team file rather than using another loop to calculate
                    foreach (var player in team.Players)
                    {
                        teamTPE += player.PlayerTPE;
                    }
                    team.TeamTPE = teamTPE;

                    viewModel.Teams.Add(team);
                }
            }

            return View(viewModel);
        }

        public ActionResult PlayerTPE(int id)
        {
            throw new System.NotImplementedException();
        }
    }
}

NSFL/NSFL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NSFL/NSFL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NSFL Advanced Stats | @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @if (IsSectionDefined("Styles")) {
        @RenderSection("Styles", required: false)}
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NSFL Advanced Stats", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Team TPE", "TeamTPE", "Stats")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/d3")
    @RenderSection("scripts", required: false)
</body>
</html>

NSFL/NSFL/Views/Stats/PlayerTPE.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

NSFL/NSFL/Views/Stats/TeamTPE.cshtml
@model NSFL.Models.Stats.TeamTPEViewModel

@{
    ViewBag.Title = "Index";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Index</h2>
        <h3>Player TPE</h3>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover playerDataTables">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => Model.AllPlayers.FirstOrDefault().PlayerSeasonDrafted)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => Model.AllPlayers.FirstOrDefault().TeamName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => Model.AllPlayers.FirstOrDefault().PlayerFullName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => Model.AllPlayers.FirstOrDefault().PlayerPosition)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => Model.AllPlayers.FirstOrDefault().PlayerTPE)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var player in Model.AllPlayers)
                                {
                                    var playerUrl = player.PlayerProfileURL.Replace("&amp;", "&");
                                    playerUrl = "http://nsfl.jcink.net/index.php?" + playerUrl.Split('&').Last();
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(teamPlayer => player.PlayerSeasonDrafted)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(teamPlayer => player.TeamName)
                                        </td>
                                        <td>
                                            <a href="@playerUrl" target="_blank">@Html.DisplayFor(teamPlayer => player.PlayerFullName)</a>
</td>
                                        <td>
                                            @Html.DisplayFor(teamPlayer => player.PlayerPosition)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(teamPlayer => player.PlayerTPE)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h3>Team TPE</h3>
    </div>
</div>

@foreach (var team in Model.Teams)
{
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">

                    <dl class="dl-vertical">
                        <dt>
                            @Html.DisplayNameFor(model => team.TeamName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => team.TeamName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => team.TeamTPE)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => team.TeamTPE)
                        </dd>
                    </dl>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => team.Players.FirstOrDefault().PlayerSeasonDrafted)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => team.Players.FirstOrDefault().PlayerFullName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => team.Players.FirstOrDefault().PlayerPosition)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => team.Players.FirstOrDefault().PlayerTPE)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var player in team.Players)
                                {
                                    var playerUrl = player.PlayerProfileURL.Replace("&amp;", "&");
                                    playerUrl = "http://nsfl.jcink.net/index.php?" + playerUrl.Split('&').Last();
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(teamPlayer => player.PlayerSeasonDrafted)
                                        </td>
                                        <td>
                                            <a href="@playerUrl" target="_blank">@Html.DisplayFor(teamPlayer => player.PlayerFullName)</a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(teamPlayer => player.PlayerPosition)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(teamPlayer => player.PlayerTPE)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/d3scripts")

    <script type="text/javascript">
        $(document).ready(function () {

            $('.playerDataTables').DataTable({
                pageLength: 10,
                dom: '<"html5buttons"B>lTfgitp',
                order: [[4, "desc"]],
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'NSFL Player Export' },
                ]

            });

            $('.dataTables').DataTable({
                pageLength: 10,
                dom: '<"html5buttons"B>lTfgitp',
                order: [[3, "desc"]],
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'NSFL Player Export' },
                ]

            });
        });
    </script>
}